export type ItemCatalogueSpec = {
  slug: string;
  title: string;
  summary: string;
  categories: string[];
  aliases?: string[];
};

export const itemCatalogueSpecs: ItemCatalogueSpec[] = [
  { slug: 'copper-ore', title: 'Copper Ore', summary: 'A basic mining ore used to make Bronze Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'tin-ore', title: 'Tin Ore', summary: 'A basic mining ore used with Copper Ore to make Bronze Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'iron-ore', title: 'Iron Ore', summary: 'A mining ore used to make Iron Bars and Steel Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'mithril-ore', title: 'Mithril Ore', summary: 'A high-tier mining ore used to make Mithril Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'silver-ore', title: 'Silver Ore', summary: 'A valuable mining ore used to make Silver Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'gold-ore', title: 'Gold Ore', summary: 'A valuable mining ore used to make Gold Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'gold-dust', title: 'Gold Dust', summary: 'A mining resource that can be smelted into Gold Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'ebony-ore', title: 'Ebony Ore', summary: 'A high-tier mining ore used to make Ebony Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'ebony-dust', title: 'Ebony Dust', summary: 'A high-tier mining resource that can be smelted into Ebony Bars.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'essence-geode', title: 'Essence Geode', summary: 'A mining find that can be processed into a large amount of Essence.', categories: ['Items', 'Mining', 'Potion Making', 'Materials'] },
  { slug: 'minnow', title: 'Minnow', summary: 'An early fish used for fishing and Potion Making processing.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'common-trout', title: 'Common Trout', summary: 'An early fish processed into Scrap Fish Flesh and a Small Essence Gland.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'perch', title: 'Perch', summary: 'A fish processed into Fish Scales and a Small Essence Gland.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'bass', title: 'Bass', summary: 'A fish processed into Plain Fish Flesh and a Small Essence Gland.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'blue-gill', title: 'Blue Gill', summary: 'A fish processed into Essence Glands.', categories: ['Items', 'Fishing', 'Materials'], aliases: ['Bluegill'] },
  { slug: 'elder-trout', title: 'Elder Trout', summary: 'A fish processed into Hearty Fish Flesh and an Essence Gland.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'small-essence-gland', title: 'Small Essence Gland', summary: 'A small gland processed into Essence at a Reduction Station.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'essence-gland', title: 'Essence Gland', summary: 'A gland processed into Essence at a Reduction Station.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'large-essence-gland', title: 'Large Essence Gland', summary: 'A large gland processed into Essence at a Reduction Station.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'rare-minnow', title: 'Rare Minnow', summary: 'An oily fish processed into Fish Oil for Fishing Potions.', categories: ['Items', 'Fishing', 'Potion Making', 'Materials'] },
  { slug: 'rare-blue-gill', title: 'Rare Blue Gill', summary: 'An oily fish processed into high-yield Fish Oil.', categories: ['Items', 'Fishing', 'Potion Making', 'Materials'] },
  { slug: 'spider-eye', title: 'Spider Eye', summary: 'A monster drop processed into Distilled Spider Eye.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'hearty-fish-mash', title: 'Hearty Fish Mash', summary: 'A hearty fish ingredient reduced into Hearty Extract.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'hardened-fish-scales', title: 'Hardened Fish Scales', summary: 'Fish scales reduced into Polished Fish Scales.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'fish-oil', title: 'Fish Oil', summary: 'An oily Potion Making ingredient used to brew Fishing Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'distilled-spider-eye', title: 'Distilled Spider Eye', summary: 'A processed ingredient used to brew Archery Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'hearty-extract', title: 'Hearty Extract', summary: 'A processed ingredient used to brew Strong Health Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'polished-fish-scales', title: 'Polished Fish Scales', summary: 'Processed scales used to make Fine Fish Scales.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'fish-scales', title: 'Fish Scales', summary: 'Perch scales used to make Crushed Fish Scales.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'crushed-fish-scales', title: 'Crushed Fish Scales', summary: 'A processed ingredient used in Shields Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'mud-root', title: 'Mud Root', summary: 'A plant ingredient crushed into Root Paste.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'root-paste', title: 'Root Paste', summary: 'A processed ingredient used in Mining Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'plain-fish-flesh', title: 'Plain Fish Flesh', summary: 'Bass flesh crushed into Fish Mash.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'fish-mash', title: 'Fish Mash', summary: 'A processed ingredient used in Health Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'small-fang', title: 'Small Fang', summary: 'A monster drop crushed into Fang Dust.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'fang-dust', title: 'Fang Dust', summary: 'A processed ingredient used in Attack Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'glowing-mushroom', title: 'Glowing Mushroom', summary: 'A mushroom crushed into Crushed Mushroom for Magic Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'crushed-mushroom', title: 'Crushed Mushroom', summary: 'A processed ingredient used in Magic Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'hearty-fish-flesh', title: 'Hearty Fish Flesh', summary: 'Elder Trout flesh crushed into Hearty Fish Mash.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'fine-fish-scales', title: 'Fine Fish Scales', summary: 'A final processed fish ingredient used in Strong Shields Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'scrap-fish-flesh', title: 'Scrap Fish Flesh', summary: 'A basic fish ingredient used in Weak Health Potions.', categories: ['Items', 'Potion Making', 'Materials'] },
  { slug: 'weak-health-potion', title: 'Weak Health Potion', summary: 'A basic potion brewed from Scrap Fish Flesh and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'fishing-potion', title: 'Fishing Potion', summary: 'A potion brewed from Fish Oil and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'shields-potion', title: 'Shields Potion', summary: 'A potion brewed from Crushed Fish Scales and Essence.', categories: ['Items', 'Potion Making', 'Potions'], aliases: ['Shield Potion'] },
  { slug: 'mining-potion', title: 'Mining Potion', summary: 'A potion brewed from Root Paste and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'health-potion', title: 'Health Potion', summary: 'A potion brewed from Fish Mash and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'attack-potion', title: 'Attack Potion', summary: 'A potion brewed from Fang Dust and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'archery-potion', title: 'Archery Potion', summary: 'A potion brewed from Distilled Spider Eye and Essence.', categories: ['Items', 'Potion Making', 'Potions'], aliases: ['Ranging Potion', 'Ranged Potion'] },
  { slug: 'magic-potion', title: 'Magic Potion', summary: 'A potion brewed from Crushed Mushroom and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'strong-health-potion', title: 'Strong Health Potion', summary: 'A stronger potion brewed from Hearty Extract and Essence.', categories: ['Items', 'Potion Making', 'Potions'] },
  { slug: 'strong-shields-potion', title: 'Strong Shields Potion', summary: 'A stronger potion brewed from Fine Fish Scales and Essence.', categories: ['Items', 'Potion Making', 'Potions'], aliases: ['Strong Shield Potion'] },
  { slug: 'small-vial', title: 'Small Vial', summary: 'A small container used to bottle potions.', categories: ['Items', 'Potion Making', 'Containers'] },
  { slug: 'large-vial', title: 'Large Vial', summary: 'A larger container used to bottle potions.', categories: ['Items', 'Potion Making', 'Containers'] },
  { slug: 'gilded-vial', title: 'Gilded Vial', summary: 'A gilded container used to bottle high-tier potions.', categories: ['Items', 'Potion Making', 'Containers'] },
  { slug: 'rough-leather', title: 'Rough Leather', summary: 'A leather material used in early Smithing equipment.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'rough-cloth', title: 'Rough Cloth', summary: 'A cloth material used in early Smithing equipment.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'thick-leather-pant-line', title: 'Thick Leather Pant Line', summary: 'A leather lining used in Steel Platelegs.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'thick-leather-vest-line', title: 'Thick Leather Vest Line', summary: 'A leather lining used in Steel Platebody.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'elven-cloth-pant-line', title: 'Elven Cloth Pant Line', summary: 'An elven cloth lining used in Mithril Platelegs.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'elven-cloth-vest-line', title: 'Elven Cloth Vest Line', summary: 'An elven cloth lining used in Mithril Platebody.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'exquisite-silk-boot-line', title: 'Exquisite Silk Boot Line', summary: 'A silk lining used to assemble Dusk Knight Boots.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'exquisite-silk-pant-line', title: 'Exquisite Silk Pant Line', summary: 'A silk lining used to assemble Dusk Knight Platelegs.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'exquisite-silk-vest-line', title: 'Exquisite Silk Vest Line', summary: 'A silk lining used to assemble Dusk Knight Platebody.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'exquisite-silk', title: 'Exquisite Silk', summary: 'A rare silk material used to make Dusk Knight linings.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'dusk-knight-schematics', title: 'Dusk Knight Schematics', summary: 'The schematic item required throughout the Dusk Knight Smithing chain.', categories: ['Items', 'Smithing', 'Quest items'] },
  { slug: 'volcanic-core', title: 'Volcanic Core', summary: 'A volcanic boss material used to make the Volcanic Ward.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'charred-ring-piece-1', title: 'Charred Ring Piece 1', summary: 'A volcanic ring component used in the Volcanic Ring recipe.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'charred-ring-piece-2', title: 'Charred Ring Piece 2', summary: 'A volcanic ring component used in the Volcanic Ring recipe.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'charred-ring-piece-3', title: 'Charred Ring Piece 3', summary: 'A volcanic ring component used in the Volcanic Ring recipe.', categories: ['Items', 'Smithing', 'Materials'] },
  { slug: 'smithing-hammer', title: 'Smithing Hammer', summary: 'A tool that must be equipped to smith at an anvil.', categories: ['Items', 'Smithing', 'Tools'] },
  { slug: 'dwarven-smithing-hammer', title: 'Dwarven Smithing Hammer', summary: 'A stronger Smithing Hammer with increased Smithing Power.', categories: ['Items', 'Smithing', 'Tools'] },
  { slug: 'copper-pickaxe', title: 'Copper Pickaxe', summary: 'A starter tool used to mine basic ore.', categories: ['Items', 'Mining', 'Tools'] },
  { slug: 'iron-pickaxe', title: 'Iron Pickaxe', summary: 'A Mining tool used to access the Iron tier.', categories: ['Items', 'Mining', 'Tools'] },
  { slug: 'steel-pickaxe', title: 'Steel Pickaxe', summary: 'A Mining tool used to access the Coal tier.', categories: ['Items', 'Mining', 'Tools'] },
  { slug: 'dwarven-pickaxe', title: 'Dwarven Pickaxe', summary: 'A Mining tool used to access Mithril mining.', categories: ['Items', 'Mining', 'Tools'] },
  { slug: 'artisan-gloves', title: 'Artisan Gloves', summary: 'Gloves that improve Smithing and Potion Making Power.', categories: ['Items', 'Smithing', 'Equipment'] },
  { slug: 'smithing-power-gem', title: 'Smithing Power Gem', summary: 'A gem that improves Smithing Power.', categories: ['Items', 'Smithing', 'Equipment'] },
  { slug: 'weak-power-gem', title: 'Weak Power Gem', summary: 'A low-tier power gem found while mining.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'power-gem', title: 'Power Gem', summary: 'A mining gem that improves equipment power.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'strong-power-gem', title: 'Strong Power Gem', summary: 'A high-tier power gem found while mining.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'fishing-power-gem', title: 'Fishing Power Gem', summary: 'A gem associated with higher-tier fishing and mining content.', categories: ['Items', 'Fishing', 'Materials'] },
  { slug: 'mining-power-gem', title: 'Mining Power Gem', summary: 'A gem that improves Mining Power.', categories: ['Items', 'Mining', 'Equipment'] },
  { slug: 'strange-gem', title: 'Strange Gem', summary: 'A rare gem found in higher-tier mining areas.', categories: ['Items', 'Mining', 'Materials'] },
  { slug: 'titanium-ring', title: 'Titanium Ring', summary: 'A ring found in high-level combat content.', categories: ['Items', 'Equipment', 'Jewellery'] },
  { slug: 'bone-ring', title: 'Bone Ring', summary: 'A ring dropped by Cavern Goblins.', categories: ['Items', 'Equipment', 'Jewellery'] },
  { slug: 'bone-mask', title: 'Bone Mask', summary: 'A mask dropped by the Cavern Goblin Hunter.', categories: ['Items', 'Equipment'] },
  { slug: 'bone-bow', title: 'Bone Bow', summary: 'A bow dropped by the Cavern Goblin Hunter.', categories: ['Items', 'Equipment', 'Weapons'] },
  { slug: 'volcanic-shard', title: 'Volcanic Shard', summary: 'A volcanic boss material dropped by The Burning King.', categories: ['Items', 'Materials'] },
  { slug: 'sword-of-the-burning-king', title: 'Sword of the Burning King', summary: 'A unique weapon associated with The Burning King.', categories: ['Items', 'Equipment', 'Weapons'] },
  { slug: 'small-worm-bait', title: 'Small Worm Bait', summary: 'Bait used by some Fishing spots.', categories: ['Items', 'Fishing', 'Bait'] },
  { slug: 'medium-worm-bait', title: 'Medium Worm Bait', summary: 'Bait used by higher-tier Fishing spots.', categories: ['Items', 'Fishing', 'Bait'] },
];
