export const commonQueryCorrections: Readonly<Record<string, string>> = {
  // Greetings and common question words
  helo: 'hello',
  hellow: 'hello',
  hekko: 'hello',
  heyo: 'hello',
  yo: 'hello',
  wath: 'what',
  waht: 'what',
  wat: 'what',
  wehre: 'where',
  hwo: 'how',
  fnd: 'find',
  '1h': 'one-handed',
  '2h': 'two-handed',

  // Skills and progression
  atk: 'attack',
  atack: 'attack',
  attak: 'attack',
  atatck: 'attack',
  def: 'defence',
  deff: 'defence',
  deffence: 'defence',
  defense: 'defence',
  lvl: 'level',
  levl: 'level',
  experiance: 'experience',
  experiense: 'experience',
  exp: 'experience',
  magik: 'magic',
  magick: 'magic',
  archrey: 'archery',
  archeri: 'archery',
  ranging: 'archery',
  minning: 'mining',
  mineing: 'mining',
  fising: 'fishing',
  fishng: 'fishing',
  smithig: 'smithing',
  smthing: 'smithing',
  makeing: 'making',
  potoin: 'potion',
  poton: 'potion',
  potionmaking: 'potion making',

  // Materials and crafting
  mith: 'mithril',
  myth: 'mithril',
  copr: 'copper',
  bronse: 'bronze',
  oron: 'iron',
  stel: 'steel',
  sheild: 'shield',
  sheilds: 'shields',
  essance: 'essence',
  cauldran: 'cauldron',
  gildid: 'gilded',
  recipie: 'recipe',
  recipies: 'recipes',
  blaksmith: 'blacksmith',
  sel: 'sell',
  byu: 'buy',
  fng: 'fang',
  roto: 'root',

  // Creatures and names
  gobln: 'goblin',
  gblin: 'goblin',
  brserker: 'berserker',
  pierate: 'pirate',
  allice: 'alice',
  alise: 'alice',
  enemys: 'enemies',
  bos: 'boss',
  boses: 'bosses',
  ashan: 'ashen',
  ashn: 'ashen',
  renger: 'ranger',
  rengers: 'rangers',
  rangr: 'ranger',
  warror: 'warrior',
  archr: 'archer',
  skelton: 'skeleton',
  gobblin: 'goblin',
  cavren: 'cavern',
  cavarn: 'cavern',
  cristal: 'crystal',
  kil: 'kill',
  kils: 'kills',

  // Equipment
  bwo: 'bow',
  staf: 'staff',
  stave: 'staff',
  swodr: 'sword',
  sowrd: 'sword',
  amullet: 'amulet',
  ammy: 'amulet',
  rign: 'ring',
  trinkt: 'trinket',
  trnket: 'trinket',
  armor: 'armour',
  armoir: 'armour',
  armuor: 'armour',
};

export function normalizePlayerQuery(value: string) {
  return value.replace(/[A-Za-z0-9']+/g, (token) => commonQueryCorrections[token.toLowerCase()] ?? token);
}
